### ISSUE TITLE
bugs in astro

### ISSUE THREAD

**Issue by danieljsaldana** [giuseppelt/feelback-integrations#2]
When using any version of 3.x it is impossible to compile when using astro

**Comment by giuseppelt** [comment]
Sorry, I missed the bump to 3 or it’s a prerelease thing?
In any case which component or scenario are you using?
________________________________
From: Daniel J. Saldaña ***@***.***>
Sent: Monday, July 31, 2023 9:47:38 PM
To: giuseppelt/feelback-integrations ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [giuseppelt/feelback-integrations] bugs in astro (Issue #2)


When using any version of 3.x it is impossible to compile when using astro

**Comment by giuseppelt** [comment]
Hi, just updated astro-feelback to v0.3.3
Let me know if it works.
And would like to know what case are you using. Thanks!

**Comment by danieljsaldana** [comment]
It already compiles, but there is the same bug as in 2.x and that is that only the feel face icon works. The rest indicates that the value you are trying to send back does not seem to be valid.

I am using FeelbackReaction and github icons

Thank you very much for your response so quickly!

I have created another issue for this bug

<img width="883" alt="image" src="https://github.com/giuseppelt/feelback-integrations/assets/28693020/5f3a15ca-0e72-446b-ba89-584f2c01acf3">
