### ISSUE TITLE
`feelback-integrations/samples/astro-starlight` crashing on `pnpm dev`

### ISSUE THREAD

**Issue by robmunger** [giuseppelt/feelback-integrations#4]
Hi, I attempted to sample `feelback-integrations/samples/astro-starlight`.  After running pnpm install and pnpm dev, I got a flurry of errors and the dev server wouldn't load on localhost.

Is it possible that the Astro integration needs an update for newer versions of Astro? 

I also had similar bugs when I followed your Astro-Starlight integration tutorial in my own code, but I thought the sample project would be easier for you to test.

Thanks for what looks like a great product. Hoping I can get it working...

**Comment by giuseppelt** [comment]
Sorry. Yeah I think you're right. I'll have a look and update them with the latest version of astro/starlight.

**Comment by robmunger** [comment]
Much appreciated! Astro has had a lot of development recently and I'm really looking forward to trying my feelback widget out.

**Comment by giuseppelt** [comment]
Hi, just pushed d2e7a8f7506b743a063146b5d5d28e55cc41dedb.
I updated the samples/astro-starlight to the latest version with the new method to override components.

Just take a look at [astro.config.mjs](https://github.com/giuseppelt/feelback-integrations/blob/d2e7a8f7506b743a063146b5d5d28e55cc41dedb/samples/astro-starlight/astro.config.mjs#L31) on how the new integration works.

I will update the documentation in the next days.
